import Link from "next/link";
import {POLICY_VERSION} from "@/lib/policies";
import {PolicyContact} from "@/components/policy-contact";
export const metadata={title:"Privacy · JevArena"};
export default function Privacy(){return <main id="main" className="prose-page policy-page">
  <h1>Privacy</h1><p>Policy version: {POLICY_VERSION}</p><PolicyContact/>
  <h2>Playing as a guest</h2><p>Your question, possible answers and any necessary context are sent to the selected AI providers when you explicitly run an experiment. OpenRouter calls currently go directly from your browser to OpenRouter. Providers process your content under their own policies. Do not submit passwords, confidential documents or sensitive personal information.</p>
  <p>Guest drafts, model API keys, judgments and votes stay in the current tab unless you explicitly save, contribute, download or share them. Refreshing clears the in-memory state. API keys are not saved to an account, research submission or share link. This is not a promise that provider or hosting infrastructure keeps no operational logs.</p>
  <h2>Optional account and private history</h2><p>When enabled, email sign-in uses Supabase Auth and a configured email-delivery service to send a one-time login link. The account contains your email and identity identifier. Your email is used for authentication and service messages, not a marketing subscription. Essential session cookies keep you signed in; they are separate from your model API key.</p>
  <p>Only clicking Save privately after its separate checkbox uploads the selected question, answers, model results and vote to your account history. Logging in does not upload the current conversation automatically. History is private to your account in the application, not public or end-to-end encrypted; authorized infrastructure administrators may access stored data for operations and support. The service limits history to 100 experiments per account and retains each for up to 30 days.</p>
  <p>Download or delete saved experiments from <Link href="/history">Your history</Link>. Expired items are excluded from reads immediately and removed by scheduled cleanup. Deletion removes active records; restricted infrastructure backups may retain copies until their normal expiry. Account deletion requests require identity verification through the private contact channel above.</p>
  <h2>Research contributions are a separate choice</h2><p>Saving private history is not research consent. Research submission separately asks you to review the content, confirm rights and agree to the displayed contribution license. The intake stores the submitted task, runs, vote when supplied, consent version and timestamp. It also uses a salted IP hash for abuse limits; hosting providers may process IP addresses. Private research submissions remain untrusted, are retained for up to 30 days, and are not automatically published or used to run later paid evaluations.</p>
  <p>Use your downloaded deletion receipt at <Link href="/contributions/delete">Withdraw a contribution</Link>. Keep the receipt secret. Minimal receipt and abuse-prevention metadata may remain to prevent accidental resubmission. Public GitHub contributions and reviewed case pages require a separate deliberate publication workflow.</p>
  <h2>Sharing and public data</h2><p>Instant share links contain approved experiment data in their URL fragment. Anyone with the link can read or copy it. Downloaded JSON and images are controlled by whoever receives them. Public GitHub content and published case studies can be copied or archived by others; removing our copy cannot recall those copies.</p>
  <h2>Infrastructure, cookies and security</h2><p>Vercel hosts the site and functions; Supabase provides account and database infrastructure when configured; the authentication email-delivery service processes recipient addresses and login emails; selected AI providers process model requests. These services may process data outside your country. We use HTTPS, access controls, server-only credentials and owner-scoped database access. No system is risk-free. We do not intentionally log request bodies or API keys.</p>
  <p>There is no marketing subscription, advertising tracker or reCAPTCHA in this release. Essential login cookies may remain until sign-out or expiry. Provider sites reached through external links have their own practices. Changes to processing will be reflected in a revised policy and appropriate new choices before new uses.</p>
</main>;}
