import Link from "next/link";
import {POLICY_VERSION} from "@/lib/policies";
import {PolicyContact} from "@/components/policy-contact";
export const metadata={title:"Terms · JevArena"};
export default function Terms(){return <main id="main" className="prose-page policy-page">
  <h1>Terms of use</h1><p>Version: {POLICY_VERSION}</p><PolicyContact/>
  <h2>The service</h2><p>JevArena is an independent experimental interface for comparing model judgments. It is not affiliated with Arena or the model providers. Browsing examples does not require an account. Using the model interface requires your own authorized provider key and agreement to these terms. Read our <Link href="/privacy">Privacy Policy</Link> before submitting content.</p>
  <h2>Your content and responsibilities</h2><p>Use only content and credentials you have permission to use. Do not submit sensitive personal data or secrets as task content, infringe others’ rights, conduct unlawful activity, bypass access controls or abuse service limits. You must meet the age and eligibility requirements of the services you use. This service is not intended for children under 18.</p>
  <p>You retain your rights in your content. You permit the processing needed to execute your requested comparison and any private save or sharing action you choose. When public contribution mode is enabled, its visible checkbox starts on. Leaving it on when completing an answer or vote authorizes research use and publication after review of the displayed task, your answer or reason, and associated model results or preference vote. Turn it off before proceeding to exclude that activity from research collection. No page load or provider connection grants this permission.</p>
  <p>Original public contributions are licensed under CC BY 4.0 with attribution; third-party material retains its original license and source. Do not contribute material you lack permission to share. A public candidate is held in a review queue, not automatically displayed. Existing private contributions remain private, and the separate private-research form does not authorize publication. These permissions do not authorize model training or later paid provider calls.</p>
  <h2>Provider billing</h2><p>You are responsible for charges incurred through your provider account, including unsuccessful or cancelled requests already processed upstream. Estimates are informational, not billing caps. No automatic paid retries are made by this interface. Prices, access and provider behavior can change.</p>
  <h2>Experimental results</h2><p>Models may be wrong, biased or inappropriate. Verify important outputs independently. Results are not professional advice. Human answers and optional reasons are unverified observations; community votes express preference, not proven correctness. Browser submissions are not trusted benchmark evidence. We do not promise availability, accuracy or fitness for a particular purpose.</p>
  <h2>Accounts, retention and availability</h2><p>Optional accounts are for explicitly saved private history. Protect your email account and do not share login links or sessions. Export important records: history has a 30-day retention window and capacity limits, and is not a permanent archive. We may restrict abusive use or temporarily suspend features for security and capacity reasons.</p>
  <p>Pending research contributions expire after 30 days. Keep your deletion receipt to withdraw the pending payload. Reviewed public GitHub cases can persist beyond this window; removing our copy cannot recall forks, archives or other copies. Contact the operator privately about published material. Public collection remains gated until its database and deployment checks pass.</p>
  <h2>Changes and your rights</h2><p>Updated terms will carry a new version. Materially different data uses require an appropriate new notice or choice. Nothing here excludes rights or liabilities that cannot lawfully be excluded. Contact the operator above for questions, privacy requests or account deletion.</p>
</main>;}
